### PR TITLE
Level rewrite

### PR DESCRIPTION
**Pull request by PEMapModder**
Level Rewrite: [Build Status](https://travis-ci.org/BlockServerProject/BlockServer)
# TODO:
- [ ] Implement level saving
  - [ ] Anvil format `L.P.`
  - [x] BlockServer level format
- [ ] World generation
  - [ ] Implement Flat World Generator.
    - [x] preset parsing
    - [x] basic generation
    - [ ] populate structures
  - [ ] Implement normal world generator `L.P.`
- [x] Implement chunks sending
  - [x] Implement FullChunkDataPacket
  - [x] Implement proper chunk sending order

### CODE REVIEW

**Comment by jython234** [comment]
It's fun looking back at this old stuff... Hard to believe how active everyone was...

**Comment by AndreyNazarchuk** [comment]
Yay active again!

**Comment by jython234** [comment]
@AndreyNazarchuk I am expecting player spawning to be functional within a few days on the ```network``` branch for 0.11.0.

**Comment by AndreyNazarchuk** [comment]
Horray! Is there a tutorial/api for plugin making yet?

**Comment by jython234** [comment]
That is assuming everything goes as planned. As for the plugins, I have no
idea about the api yet. I'm not sure weather to include PocketBukkit in
this, or to just implement a plugin api here in BlockServer.

On Sunday, May 31, 2015, Andrey Nazarchuk <notifications@github.com> wrote:

> Horray! Is there a tutorial/api for plugin making yet?
> On May 31, 2015 6:23 PM, "jython234" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > @AndreyNazarchuk <https://github.com/AndreyNazarchuk> I am expecting
> > player spawning to be functional within a few days on the network branch
> > for 0.11.0.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/BlockServerProject/BlockServer/pull/98#issuecomment-107277261
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/pull/98#issuecomment-107277986>
> .
>


--

**Comment by optrusty** [comment]
Oh the good old days...

**Comment by jython234** [comment]
@optrusty Hopefully, the "good old days" will return this summer.

**Comment by optrusty** [comment]
@jython234 For me the end of school is June 19th and my graduation is 16th

**Comment by jython234** [comment]
Don't put stuff like that on github xD. I am expecting to do full
development on BlockServer around that time.

On Monday, June 1, 2015, Yafeat Alemayhu <notifications@github.com> wrote:

> @jython234 For me the end of school is June 19th and my graduation is 16th
>
> On Mon, Jun 1, 2015 at 7:14 PM, jython234 <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > @optrusty <https://github.com/optrusty> Hopefully, the "good old days"
> > will return this summer.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/BlockServerProject/BlockServer/pull/98#issuecomment-107743521
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/pull/98#issuecomment-107769322>
> .
>


--

**Pull request closed without merging**
