### PR TITLE
Update Event.java

### PR DESCRIPTION
**Pull request by xpyctum**
I'm think that better

### CODE REVIEW

**Comment by jython234** [comment]
We may delete the file Event.java. Still don't really see its purpose.

On Sunday, February 1, 2015, Oleg Basalyga <notifications@github.com> wrote:

> I'm think that better
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/BlockServerProject/BlockServer/pull/132
> Commit Summary
>
>    - Update Event.java
>
> File Changes
>
>    - *M* src/main/java/org/blockserver/api/Event.java
>    <https://github.com/BlockServerProject/BlockServer/pull/132/files#diff-0>
>    (2)
>
> Patch Links:
>
>    - https://github.com/BlockServerProject/BlockServer/pull/132.patch
>    - https://github.com/BlockServerProject/BlockServer/pull/132.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/pull/132>.
>


--

**Comment by xpyctum** [comment]
@jython234  THIS IS MUST BE CHANGED!!! :D

**Comment by PEMapModder** [comment]
We are not going to implement the API through BlockServer, but through @PocketBukkit/PocketBukkit. This package shall be rewritten, so changes to it right now are pointless.

**Comment by jython234** [comment]
@PEMapModder sorry for the misinterpretation of your idea. The API
interface is correct I assume?

On Sunday, February 1, 2015, PEMapModder <notifications@github.com> wrote:

> We are not going to implement the API through BlockServer, but through
> @PocketBukkit/PocketBukkit. This package shall be rewritten, so changes to
> it right now are pointless.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/pull/132#issuecomment-72371535>
> .
>


--

**Comment by PEMapModder** [comment]
Well, I expected that either one of these be implemented:

1. In the starter of PocketBukkit, create a new `Server` instance, call `server.useAPI(new PocketBukkit(server))` and start the server
2. Set a property in server.properties called `api-classname`, check in `Server` constructor, if it is a class name, instantiate a new instance of that class with `Server` as the parameter
3. Load PocketBukkit as a library, call a method in PocketBukkit (maybe specified in a library manifest), and that method will inject the API into the server using similar method as 1.

**Comment by jython234** [comment]
I implemented 1 I believe. Download a copy of the "new" branch on
pocketbukkit and run. It works well.

On Sun, Feb 1, 2015 at 11:14 AM, PEMapModder <notifications@github.com>
wrote:

> Well, I expected that either one of these be implemented:
>
>    1. In the starter of PocketBukkit, create a new Server instance, call server.useAPI(new
>    PocketBukkit(server)) and start the server
>    2. Set a property in server.properties called api-classname, check in
>    Server constructor, if it is a class name, instantiate a new instance
>    of that class with Server as the parameter
>    3. Load PocketBukkit as a library, call a method in PocketBukkit
>    (maybe specified in a library manifest), and that method will inject the
>    API into the server using similar method as 1.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/pull/132#issuecomment-72373444>
> .
>



-- 
Your friend ...

**Pull request closed without merging**
