### PR TITLE
Networking Update (Do not merge until ready)

### PR DESCRIPTION
**Pull request by jython234**
#### Planned changes:
- [x] Rewrite all RakNet code
- [ ] Implement 0.11.0
  - [x] Implement client sent split packets.
  - [x] Implement BatchPackets.
  - [ ] Implement 0.11.0 new packets
    - [ ] Text Packet (Chat)
    - [x] Play Status Packet
  - [ ] Implement chunk sending.

Contribute by pushing commits to the ```network``` branch.

### CODE REVIEW

**Comment by jython234** [comment]
#### Status Update:
Client Split packets are complete (not tested).
Client Batch Packets are complete (tested).
RakNet code rewritten.

**Comment by PEMapModder** [comment]
@jython234 IRC pls

**Comment by jython234** [comment]
@PEMapModder I'm on.

**Comment by jython234** [comment]
I'm re-creating the branch, as this has conflicts and I think it's a bit messy.

**Pull request closed without merging**
